### ISSUE TITLE
Coinmaster multiple minters consideration

### ISSUE THREAD

**Issue by matpb** [noria-net/noria#13]
In its current implementation, the Coinmaster module allows only one minter to be whitelisted.
Do we want to consider upgrading this to support multiple minters? @jumpdest7d

**Comment by FrankBoltzmann** [comment]
Go ahead with this Mat, I'm creating a Notion task for this issue too.

**Comment by matpb** [comment]
Closed by https://github.com/noria-net/noria/pull/14
